### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 1ain00** [1ain00/git-app#6]
https://protospace-38440.herokuapp.com/

**Comment by soll02solglas** [comment]
@1ain00 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう。
現状そのユーザー以外が投稿したプロトタイプも表示されています。
<img width="1073" alt="スクリーンショット 2022-09-12 9 11 20" src="https://user-images.githubusercontent.com/30042165/189555097-f0f95ae1-7a3d-4f22-b008-6a0e2bb10362.png">

- [x] コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。
空のまま投稿するとエラーページに遷移してしまいます。
<img width="581" alt="スクリーンショット 2022-09-12 9 14 08" src="https://user-images.githubusercontent.com/30042165/189555172-38877419-01c4-41a4-8c0e-3d71d7e06332.png">

- [x] ログイン状態の投稿者だけが、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう。
 現状、投稿者以外のユーザーもプロトタイプを削除できてしまいます。

- [x] ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう
 現状、他のユーザーのプロトタイプ編集ページに遷移して編集できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
■■どちらかを使用 (不要な部分は削除してから送付すること)■■
■エンジニア転職■　https://forms.gle/ZdLeprTTWhMA8aZA7
■月額コース■　https://forms.gle/8UWFCx5TouRMCf756

**Comment by 1ain00** [comment]
#URL
https://protospace-38440.herokuapp.com/

**Comment by shodai-ito** [comment]
@1ain00 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
